# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Node.js 20 image as a build stage
FROM node:20-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy all source files
COPY . .

# Build the project
RUN npm run build

# Use the official Node.js 20 image for the production environment
FROM node:20-alpine AS production

# Set the working directory
WORKDIR /app

# Copy the build artifacts and node_modules from the builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/node_modules /app/node_modules
COPY package.json .

# Set environment variables (Make sure to replace with your actual key when running the container)
ENV FR24_API_KEY=your_actual_api_key_here
ENV FR24_API_URL=https://fr24api.flightradar24.com

# Expose port if needed
EXPOSE 3000

# Start the server
CMD ["node", "dist/index.js"]
